##########
# System #
##########
version: "3.6"

services:
   # The load balancer
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
            - thenet
    depends_on:
      - web
  web:
    image: web_service:1.0
    container_name: "web_service"    
    ports:
      - "3000:3000"  
    networks:
      - thenet 
    environment:
      - HOST_NAME=web 
networks:
    thenet: