##########
# System #
##########
version: "3"

services:
   # The load balancer
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"   
    depends_on:
      - web
    
  web:
    image: web_service:1.0
    container_name: "web_service"    
    ports:
      - "3000:3000"     
    environment:
      - HOST_NAME=web
      - REDIS_HOST_NAME=redis
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis:6.0.7
    container_name: redis
    # command: ["redis-server", "--bind", "redis", "--port", "6379"]    
    ports:
      - "6379:6379"
    volumes:
      # - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf 
#Remove network solve the issue where nodejs cannot access redis
# networks:
#     thenet:
volumes:
  redis-data:
  redis-conf: